<a href="https://colab.research.google.com/github/sujata1606/Data-Science-Practice/blob/main/sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note**
*   Classification - predicting whether a sample is one thing or another
*   Regression - predicting a number


In [1]:
# Standard imports
%matplotlib inline
import pandas as pd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [44]:
hd = pd.read_csv("heart_disease.csv")
hd

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[303 rows x 14 columns]

In [ ]:
hd.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [ ]:
hd.tail()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[5 rows x 14 columns]

Random Forest Classifier Workflow for Classifying Heart Disease

In [5]:
# Create X (features matrix)
X = hd.drop("target", axis=1)

# Create y (labels)
y = hd["target"]

In [6]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [8]:
# Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

In [9]:
# hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [10]:
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [11]:
X_train

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
249   69    1   2       140   254  ...      0      2.0      1   3     3
251   43    1   0       132   247  ...      1      0.1      1   4     3
75    55    0   1       135   250  ...      0      1.4      1   0     2
296   63    0   0       124   197  ...      1      0.0      1   0     2
69    62    0   0       124   209  ...      0      0.0      2   0     2
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
201   60    1   0       125   258  ...      1      2.8      1   1     3
158   58    1   1       125   220  ...      0      0.4      1   4     3
166   67    1   0       120   229  ...      1      2.6      1   2     3
58    34    1   3       118   182  ...      0      0.0      2   0     2
277   57    1   1       124   261  ...      0      0.3      2   0     3

[242 rows x 13 columns]

In [12]:
y_train

249    0
251    0
75     1
296    0
69     1
      ..
201    0
158    1
166    0
58     1
277    0
Name: target, Length: 242, dtype: int64

In [13]:
X_test.head()

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
57    45    1   0       115   260  ...      0      0.0      2   0     2
282   59    1   2       126   218  ...      0      2.2      1   1     1
281   52    1   0       128   204  ...      1      1.0      1   0     0
247   66    1   1       160   246  ...      1      0.0      1   3     1
215   43    0   0       132   341  ...      1      3.0      1   0     3

[5 rows x 13 columns]

In [14]:
y_preds = clf.predict(X_test)
y_preds

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0])

In [15]:
# Evaluate the model on the training set
clf.score(X_train, y_train)

1.0

In [16]:
# Evaluate the model on the test set
clf.score(X_test, y_test)

0.7704918032786885

In [17]:
# Other evaluation methods
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.77      0.65      0.71        26
           1       0.77      0.86      0.81        35

    accuracy                           0.77        61
   macro avg       0.77      0.76      0.76        61
weighted avg       0.77      0.77      0.77        61



In [18]:
#confusion matrix
conf_mat = confusion_matrix(y_test, y_preds)
conf_mat

array([[17,  9],
       [ 5, 30]])

In [19]:
accuracy_score(y_test, y_preds)

0.7704918032786885

**To improve model try with different hyperparameters**

In [ ]:
# Try different numbers of estimators (no cross-validation)
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {model.score(X_test, y_test) * 100}%")
    print("")

Trying model with 10 estimators...
Model accuracy on test set: 86.88524590163934%

Trying model with 20 estimators...
Model accuracy on test set: 91.80327868852459%

Trying model with 30 estimators...
Model accuracy on test set: 83.60655737704919%

Trying model with 40 estimators...
Model accuracy on test set: 88.52459016393442%

Trying model with 50 estimators...
Model accuracy on test set: 91.80327868852459%

Trying model with 60 estimators...
Model accuracy on test set: 88.52459016393442%

Trying model with 70 estimators...
Model accuracy on test set: 91.80327868852459%

Trying model with 80 estimators...
Model accuracy on test set: 88.52459016393442%

Trying model with 90 estimators...
Model accuracy on test set: 90.1639344262295%



In [ ]:
# With cross-validation
from sklearn.model_selection import cross_val_score
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {model.score(X_test, y_test) * 100}%")
    print(f"Cross-validation score: {np.mean(cross_val_score(model, X, y, cv=5)) * 100}%")
    print("")

Trying model with 10 estimators...
Model accuracy on test set: 86.88524590163934%
Cross-validation score: 78.53551912568305%

Trying model with 20 estimators...
Model accuracy on test set: 88.52459016393442%
Cross-validation score: 79.84699453551912%

Trying model with 30 estimators...
Model accuracy on test set: 88.52459016393442%
Cross-validation score: 80.50819672131148%

Trying model with 40 estimators...
Model accuracy on test set: 86.88524590163934%
Cross-validation score: 82.15300546448088%

Trying model with 50 estimators...
Model accuracy on test set: 85.24590163934425%
Cross-validation score: 81.1639344262295%

Trying model with 60 estimators...
Model accuracy on test set: 81.9672131147541%
Cross-validation score: 83.47540983606557%

Trying model with 70 estimators...
Model accuracy on test set: 90.1639344262295%
Cross-validation score: 81.83060109289617%

Trying model with 80 estimators...
Model accuracy on test set: 91.80327868852459%
Cross-validation score: 82.814207650273

**Hyperparameter tuning with GridSearchCV**

In [ ]:
# GridSearchCV
np.random.seed(42)
from sklearn.model_selection import GridSearchCV

# Define the parameters to search over
param_grid = {'n_estimators': [i for i in range(10, 100, 10)]}

# Setup the grid search
grid = GridSearchCV(RandomForestClassifier(),
                    param_grid,
                    cv=5)

# Fit the grid search to the data
grid.fit(X, y)


GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rando

In [ ]:
# Find the best parameters
grid.best_params_

{'n_estimators': 80}

In [ ]:
# Set the model to be the best estimator
clf = grid.best_estimator_
clf

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=80,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
# Fit the best model
clf = clf.fit(X_train, y_train)

In [ ]:
# Find the best model scores
clf.score(X_test, y_test)

0.9180327868852459

**Save the model**

In [ ]:
import pickle

# Save an existing model to file
pickle.dump(model, open("random_forest_model_1.pkl", "wb"))

In [ ]:
# Load a saved model and make a prediction
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.score(X_test, y_test)


0.8688524590163934

**Filling data or disregarding missing values**

In [23]:
#Import data 
missing_data = pd.read_csv("/content/car-sales-missing-data.csv")
missing_data

Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [26]:
missing_data.isna().sum()

Make        1
Colour      1
Odometer    4
Doors       1
Price       2
dtype: int64

***Using One Hot Encoding***

In [29]:
# Let's convert the categorical columns to one hot encoded (code copied from above)
# Turn the categories (Make and Colour) into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                 one_hot, 
                                 categorical_features)],
                                 remainder="passthrough")
transformed_X = transformer.fit_transform(missing_data)
transformed_X

ValueError: ignored

Fill missing data with pandas

In [30]:
# Fill the "Make" column
missing_data["Make"].fillna("missing", inplace=True)

In [31]:
# Fill the "Colour" column
missing_data["Colour"].fillna("missing", inplace=True)

In [35]:
# Fill the "Odometer (KM)" column
missing_data["Odometer"].fillna(missing_data["Odometer"].mean(), inplace=True)

In [36]:
# Fill the "Doors" column
missing_data["Doors"].fillna(4, inplace=True)

In [37]:
# Remove rows with missing Price labels
missing_data.dropna(inplace=True)

In [38]:
missing_data.isna().sum()

Make        0
Colour      0
Odometer    0
Doors       0
Price       0
dtype: int64

In [39]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                 one_hot, 
                                 categorical_features)],
                                 remainder="passthrough")
transformed_X = transformer.fit_transform(missing_data)
transformed_X

array([[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
        0.0, 150043.0, '$4,000'],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 87899.0, '$5,000'],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
        0.0, 92302.66666666667, '$7,000'],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 11179.0, '$22,000'],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
        0.0, 213095.0, '$3,500'],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 92302.66666666667, '$4,500'],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0,
        0.0, 92302.66666666667, '$7,500'],
       [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
        0.0, 31600.0, '$9,700']], dtype=object)

In [40]:
transformed_X[0]

array([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
       0.0, 150043.0, '$4,000'], dtype=object)

In [ ]:
# Split into X & y
X = missing_data.drop("Price", axis=1)
y = missing_data["Price"]

In [46]:
# Split data into train and test
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

Let's try the Random Forst Regressor

In [48]:
# Now we've transformed X, let's see if we can fit a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

# Make sure to use transformed (filled and one-hot encoded X data)
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.5300502155172415