<a href="https://colab.research.google.com/github/sujata1606/Data-Science-Practice/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Importing Numpy Library**

In [ ]:
import numpy as np

**2.Creating array**





In [ ]:
a = [10, 20, 30, 40, 50]

In [ ]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
type(a)

list

In [ ]:
x = np.array(a)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
print(x)

[10 20 30 40 50]


In [ ]:
a = [1,2,3,4,5]
b = [10,20,30,40,50]
x = np.array([a,b])

In [ ]:
print(x)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


**Array of zero**

In [ ]:
a = np.zeros((2,3))  
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


**Array of ones**

In [ ]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


**Array of your choice**

In [ ]:
np.full((2,3),10)  

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.empty((2,3))  #depends on the state of the memory

array([[0.32579155, 0.87210865, 0.53501496],
       [0.50420046, 0.53143881, 0.39726063]])

In [ ]:
np.arange(10,20)  #to create sequence of numbers

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

**Min-Max values**

In [ ]:
a = np.array([[1,4],[5,7]])
print(a)

[[1 4]
 [5 7]]


In [ ]:
np.min(a)

1

In [ ]:
np.min(a, axis=0)

array([1, 4])

In [ ]:
np.min(a, axis=1)

array([1, 5])

In [ ]:
np.max(a)

7

In [ ]:
np.max(a, axis=0)

array([5, 7])

In [ ]:
np.max(a, axis=1)

array([4, 7])

**Random numbers**

In [ ]:
a = np.random.rand(2,3)
print(a)

[[0.21008801 0.21654191 0.66633251]
 [0.15541283 0.34732182 0.32297696]]


**Shape and Reshaping**

Dimension of nparray

In [ ]:
a = [1, 2, 3, 4, 5]
x = np.array(a)
print(x)

[1 2 3 4 5]


In [ ]:
x.ndim  #dimension of an array

1

Shape of nparray

In [ ]:
a = [10, 20, 30, 40, 50]
b = [1, 2, 3, 4, 5]
x = np.array([a,b])
print(x)


[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [ ]:
x.shape  #shape of an array(row,coluumn)

(2, 5)


Reshaping an array

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,])
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a.reshape(3,3)  #to change shape of an array without changing its data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.size  #size of an array

9

In [ ]:
a = np.arange(1,7).reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


Transpose of NumPy array

In [ ]:
a = np.arange(1,16)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
b = a.reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
x = np.transpose(b)  #Reverse the axis of an array
print(x)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [ ]:
b.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

**Indexing and Slicing** 

1D Numpy Array

In [ ]:
a = np.arange(1,10)

In [ ]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a[2:5]

array([3, 4, 5])

2D Numpy Array

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a[1,2]

6

**Arithmetic Operations on NumPy Array**

In [ ]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(a+5)

[ 6  7  8  9 10 11 12 13 14 15]


In [ ]:
a - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [ ]:
b = np.arange(10,20)
print(b)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)


[11 13 15 17 19 21 23 25 27 29]
[-9 -9 -9 -9 -9 -9 -9 -9 -9 -9]
[ 10  22  36  52  70  90 112 136 162 190]
[0.1        0.18181818 0.25       0.30769231 0.35714286 0.4
 0.4375     0.47058824 0.5        0.52631579]


**Broadcasting**

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
z = a+b
print(z)

[11 13 15 17 19 21 23 25 27 29]


**Stacking and Concatenating Numpy Array**

Stacking

In [ ]:
a = np.arange(1,10)
b = np.arange(11,20)


In [ ]:
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [ ]:
x = np.hstack((a,b))   #Stack arrays in sequence horizontally
print(x)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


In [ ]:
x = np.vstack((a,b))    #Stack arrays in sequence vertically
print(x)

[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]]


Concatenating 

In [ ]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)

In [ ]:
np.concatenate((a,b))   #Join a sequence of arrays

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.concatenate((a,b), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [ ]:
np.concatenate((a,b), axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

**Aggregate Function**

In [ ]:
a = np.arange(1,14,2)
print(a)

[ 1  3  5  7  9 11 13]


In [ ]:
np.mean(a)

7.0

In [ ]:
np.median(a)

7.0

In [ ]:
np.std(a)

4.0

**Sorting**

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
x = np.sort(a)  #Return a sorted copy of an array
print(x)

[1 2 3 4 5]


In [ ]:
x = np.sort(a, kind= 'mergesort')
print(x)

[1 2 3 4 5]


**Matrix Multiplication**

In [ ]:
a = np.arange(1,10).reshape(3,3)
b = np.ones((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
np.dot(a,b)

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [ ]:
a.dot(b)

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

**Turning an image of a Panda into numbers**

In [ ]:
<img src="Pictures/download"/>

SyntaxError: ignored